# Generated by Django 5.1.15 on 2026-08-25 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('dog', '개'), ('cat', '고양이'), ('bird', '새')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
