# Generated by Django 5.2.17 on 2026-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='intro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('small', '소형'), ('medium', '중형'), ('large', '대형')], max_length=10),
        ),
    ]
