# Generated by Django 5.1.15 on 2026-08-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_age_pet_gender_pet_intro_pet_notes_pet_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['created_at']},
        ),
    ]
