upstream django_backend {
    server 127.0.0.1:8000;
}

upstream fastapi_backend {
    server 127.0.0.1:8001;
}

server {
    listen 80;
    server_name pettriage.kro.kr _;

    client_max_body_size 10M;

    # Django가 담당하는 다이어리 API
    location = /api/records {
        proxy_pass http://django_backend;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location = /api/report {
        proxy_pass http://django_backend;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }

    # AI 질의 등 나머지 API
    location /api/ {
        proxy_pass http://fastapi_backend;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }

    # 반려동물 업로드 이미지
    location /media/ {
        alias /home/ubuntu/SKN32-4th-5Team/media/;
    }

    # 화면·로그인·펫 관리 등 Django
    location / {
        proxy_pass http://django_backend;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }
}
