# Generated by Django 5.1.15 on 2026-08-25 01:16

import diary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('entry_id', models.CharField(default=diary.models._generate_entry_id, max_length=36, primary_key=True, serialize=False)),
                ('recorded_date', models.DateField()),
                ('recorded_at', models.DateTimeField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('meals', models.JSONField(blank=True, default=list)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True, null=True)),
                ('droppings', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diary_entries',
                'indexes': [models.Index(fields=['pet', 'user', 'recorded_date'], name='diary_entri_pet_id_4141ca_idx')],
            },
        ),
    ]
